# Generated by Django 5.1.4 on 2024-12-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_seller_product_seller_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='store_name',
        ),
    ]
