# Generated by Django 5.1.4 on 2024-12-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_name_seller_store_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': []},
        ),
    ]
