# Generated by Django 5.1.5 on 2025-01-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Academic Tools', 'Academic Tools'), ('Academic Coats', 'Academic Coats'), ('Student Tools', 'Student Tools'), ('Table', 'Table'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
