# Generated by Django 5.1.4 on 2025-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Academic Tools', 'Academic Tools'), ('Academic Coats', 'Academic Coats'), ('Electronics', 'Electronics'), ('Table', 'Table'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
