# Generated by Django 5.1.5 on 2025-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cartprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='chitizenship_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/chitizenship/'),
        ),
    ]
