# Generated by Django 5.1.5 on 2025-03-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
