# Generated by Django 5.1.5 on 2025-05-15 06:56
from django.db import migrations


def assign_default_phone_number(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('store', 'UserProfile')

    for user in User.objects.all():
        # Check if a UserProfile already exists to avoid duplicates
        UserProfile.objects.get_or_create(user=user, defaults={'phone_number': "980-000-0000"})


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0020_userprofile'),  # Update this to the last migration file name
    ]

    operations = [
        migrations.RunPython(assign_default_phone_number),
    ]
