# Generated by Django 5.1.5 on 2025-01-15 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('owner_phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/rooms/')),
                ('type', models.CharField(max_length=100)),
                ('noOfRooms', models.IntegerField()),
                ('moreDetails', models.TextField()),
                ('detailsBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
