# Generated by Django 5.1.5 on 2025-05-12 09:15

import rent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'Room Additional Image', 'verbose_name_plural': 'Room Additional Images'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=rent.models.room_image_upload_path, verbose_name='Main Room Image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='noOfRooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('apartment', 'Apartment'), ('hostel', 'Hostel Bed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to=rent.models.room_image_upload_path, verbose_name='Additional Image'),
        ),
    ]
