# Generated by Django 5.1.5 on 2025-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
