# Generated by Django 5.1.5 on 2025-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_room_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
