# Generated by Django 5.1.5 on 2025-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Apartment', 'Apartment'), ('Hostel', 'Hostel Bed')], max_length=100),
        ),
    ]
